from random import choice
from Narith.user.termcolor import colored

class RabbitBanners(object):
    colors = ['red', 'yellow', 'green']
    banner = colored(choice(['\n\n\n\n\n                                                              01                                                        \n                                    0  0                     0   1                                                      \n                                       0   0                  0010       0                                              \n                                     0 0   0                         10  00                                             \n                                       0   0    1         00         01  00                                             \n                                      00   0   00000   0000 0  00    01  00                                             \n                                       0   0  0    0   001  0  00  00000 001  1                                         \n                                    1  0   0 10    1   0    0  00  00     000100                                        \n                                    11 0   0 0     1  000 001  00   0     00   0                                        \n                                    0     10 0     1   00001   00   0     00   0                                        \n                                    0 0   1  0       1 000     00   0     00   0                                        \n                                 1  1     1  10  00  0 0 01    00  10   0 00   0                                        \n                                    1  0110  00  00100 0  01   00   0 10  10   0                                        \n                                 000          000  00      00       010    0   0                                        \n                                                           100                 0                                        \n                                                             0                1                                         \n                                                                                                                        \n                                                                                                                        \n                                                                                                                        \n                                                                                                                        \n']), choice(colors))


banner = RabbitBanners().banner
